openapi: 3.0.1
info:
  title: Echo service
  version: 1.0.0
paths:
  /echo/{msg}:
    get:
      operationId: getMsg
      parameters:
        - name: msg
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
